FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y make

COPY requirements.txt .
COPY Makefile .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ app/

CMD ["python", "app/main.py"]
